Setup GitHub workflow (#1)
* Trying to set up github runner workflow

see https://github.com/marketplace/actions/run-vcpkg

* vcpkg.json lowercase name

Errors occurred while parsing D:\a\FaceSwap\FaceSwap\cmakepresets\vcpkg.json
      $.name (an identifier): must be lowercase alphanumeric+hyphens and not reserved (see https://github.com/Microsoft/vcpkg/tree/master/docs/users/manifest.md for more information)

* @vcpkg.json
specify required opencv4 modules

On linux got:
 Error: gstreamer:x64-linux@1.19.2#2 is only supported on '(windows | osx) & (x64 | x86)'

opencv[gstreamer] is a module that we do not need

* next attempt at fixing vcpkg.json

* next attempt at fixing vcpkg.json

* looks like gstreamer was still pulled in as a dependency of qt / qt

vcpkg>vcpkg depend-info qt
// ...
qtmultimedia[gstreamer, qml, widgets]: angle, gstreamer, qtbase, qtdeclarative, qtshadertools
//...

* Try to fix linux CI build:

Try to install gperf before running vcpkg step

  Building package fontconfig[core]:x64-linux...
  -- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.13.94/fontconfig-2.13.94.tar.gz -> fontconfig-fontconfig-2.13.94.tar.gz...
  -- Extracting source /home/runner/work/FaceSwap/b/vcpkg/downloads/fontconfig-fontconfig-2.13.94.tar.gz
  -- Using source at /home/runner/work/FaceSwap/b/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
  CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:613 (message):
  Error:   Could not find gperf.  Please install it via your package manager.

* Try to fix linux CI build:

Try to install gperf before running vcpkg step

  Building package fontconfig[core]:x64-linux...
  -- Downloading https://gitlab.freedesktop.org/fontconfig/fontconfig/-/archive/2.13.94/fontconfig-2.13.94.tar.gz -> fontconfig-fontconfig-2.13.94.tar.gz...
  -- Extracting source /home/runner/work/FaceSwap/b/vcpkg/downloads/fontconfig-fontconfig-2.13.94.tar.gz
  -- Using source at /home/runner/work/FaceSwap/b/vcpkg/buildtrees/fontconfig/src/2.13.94-6fd83e1cbe.clean
  CMake Error at scripts/cmake/vcpkg_find_acquire_program.cmake:613 (message):
  Error:   Could not find gperf.  Please install it via your package manager.

* Try to fix linux CI build

https://github.com/microsoft/vcpkg/issues/10381
https://github.com/StefanVK/FaceSwap/runs/4513100827?check_suite_focus=true

  Building package libepoxy[core]:x64-linux...
  -- libgles2-mesa-dev must be installed before libepoxy can build. Install it with "apt-get install libgles2-mesa-dev".
  -- Downloading https://github.com/anholt/libepoxy/archive/1.5.9.tar.gz -> anholt-libepoxy-1.5.9.tar.gz...
  -- Extracting source /home/runner/work/FaceSwap/b/vcpkg/downloads/anholt-libepoxy-1.5.9.tar.gz
  -- Using source at /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean
  -- Found external ninja('1.10.2').
  -- Getting CMake variables for x64-linux-dbg
  -- Getting CMake variables for x64-linux-rel
  -- Configuring x64-linux-dbg
  -- Configuring x64-linux-dbg done
  -- Configuring x64-linux-rel
  -- Configuring x64-linux-rel done
  -- Package x64-linux-dbg
  [LogCollection][Start]File:'/home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/package-x64-linux-dbg-out.log':
  [1/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --header --no-source --outputdir=include/epoxy ../src/1.5.9-fb4e410a2d.clean/registry/glx.xml
  [2/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --header --no-source --outputdir=include/epoxy ../src/1.5.9-fb4e410a2d.clean/registry/egl.xml
  [3/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --source --no-header --outputdir=src ../src/1.5.9-fb4e410a2d.clean/registry/egl.xml
  [4/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --source --no-header --outputdir=src ../src/1.5.9-fb4e410a2d.clean/registry/glx.xml
  [5/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --header --no-source --outputdir=include/epoxy ../src/1.5.9-fb4e410a2d.clean/registry/gl.xml
  [6/14] /usr/bin/cc -Isrc/libepoxy.a.p -Isrc -I../src/1.5.9-fb4e410a2d.clean/src -Iinclude -I../src/1.5.9-fb4e410a2d.clean/include -Iinclude/epoxy -I/home/runner/work/FaceSwap/b/vcpkg_installed/x64-linux/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -fPIC -g -fPIC -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wlogical-op -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -Wno-int-conversion -MD -MQ src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o -MF src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o.d -o src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o -c src/egl_generated_dispatch.c
  FAILED: src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o
  /usr/bin/cc -Isrc/libepoxy.a.p -Isrc -I../src/1.5.9-fb4e410a2d.clean/src -Iinclude -I../src/1.5.9-fb4e410a2d.clean/include -Iinclude/epoxy -I/home/runner/work/FaceSwap/b/vcpkg_installed/x64-linux/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -fPIC -g -fPIC -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wlogical-op -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -Wno-int-conversion -MD -MQ src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o -MF src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o.d -o src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o -c src/egl_generated_dispatch.c
  In file included from ../src/1.5.9-fb4e410a2d.clean/include/epoxy/egl.h:46,
                   from ../src/1.5.9-fb4e410a2d.clean/src/dispatch_common.h:59,
                   from src/egl_generated_dispatch.c:11:
  Error: include/epoxy/egl_generated.h:11:10: fatal error: EGL/eglplatform.h: No such file or directory

* Try to fix macOS build

  autoreconf: running: aclocal --force -I m4
  Can't exec "aclocal": No such file or directory at /usr/local/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
  autoreconf: error: aclocal failed with exit status: 2

  [LogCollection][End]File:'/Users/runner/work/FaceSwap/b/vcpkg/buildtrees/libb2/autoconf-x64-osx-err.log'.
  CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
  Error:     Command failed: /usr/local/bin/autoreconf -vfi

* install python

https://github.com/StefanVK/FaceSwap/runs/4513498591?check_suite_focus=true

  Warning: [LogCollection][Warn]File not found:'Command failed: /usr/bin/python3 /home/runner/work/FaceSwap/b/vcpkg_installed/x64-linux/tools/meson/meson.py -Dwayland-backend=false -Dx11-backend=true -Dbroadway-backend=false -Dwin32-backend=false -Dmacos-backend=false -Ddemos=false -Dbuild-examples=false -Dbuild-tests=false -Dinstall-tests=false -Dgtk_doc=false -Dman-pages=false -Dintrospection=disabled -Dmedia-ffmpeg=disabled -Dmedia-gstreamer=disabled -Dprint-cups=disabled -Dvulkan=disabled -Dcloudproviders=disabled -Dsysprof=disabled -Dtracker=disabled -Dcolord=disabled --buildtype plain --backend ninja --wrap-mode nodownload --native /home/runner/work/FaceSwap/b/vcpkg/buildtrees/gtk/meson-native-x64-linux.log --default-library static --libdir lib --native /home/runner/work/FaceSwap/b/vcpkg/buildtrees/gtk/meson-native-x64-linux-debug.log'.
  CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
  Error:     Command failed: /usr/bin/python3 /home/runner/work/FaceSwap/b/vcpkg_installed/x64-linux/tools/meson/meson.py -Dwayland-backend=false -Dx11-backend=true -Dbroadway-backend=false -Dwin32-backend=false -Dmacos-backend=false -Ddemos=false -Dbuild-examples=false -Dbuild-tests=false -Dinstall-tests=false -Dgtk_doc=false -Dman-pages=false -Dintrospection=disabled -Dmedia-ffmpeg=disabled -Dmedia-gstreamer=disabled -Dprint-cups=disabled -Dvulkan=disabled -Dcloudproviders=disabled -Dsysprof=disabled -Dtracker=disabled -Dcolord=disabled --buildtype plain --backend ninja --wrap-mode nodownload --native /home/runner/work/FaceSwap/b/vcpkg/buildtrees/gtk/meson-native-x64-linux.log --default-library static --libdir lib --native /home/runner/work/FaceSwap/b/vcpkg/buildtrees/gtk/meson-native-x64-linux-debug.log -Ddebug=true --prefix /home/runner/work/FaceSwap/b/vcpkg/packages/gtk_x64-linux/debug --includedir ../include -Dcmake_prefix_path=['/home/runner/work/FaceSwap/b/vcpkg_installed/x64-linux/debug','/home/runner/work/FaceSwap/b/vcpkg_installed/x64-linux'] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/gtk/src/a0ae733b32-18e1e2c397.clean
      Working Directory: /home/runner/work/FaceSwap/b/vcpkg/buildtrees/gtk/x64-linux-dbg
      Error code: 1
      See logs for more information:
        /home/runner/work/FaceSwap/b/vcpkg/buildtrees/gtk/config-x64-linux-dbg-out.log

* xandr for linux CI build

  ../src/a0ae733b32-18e1e2c397.clean/meson.build:494:2: ERROR: Dependency "xrandr" not found, tried pkgconfig and cmake

* brew install aclocal

* still fighting missing xrandr

* libxrandr could not bet downloaded

try from warning
   Warning:   You will need to install Xorg dependencies to use feature x11:

    apt install libx11-dev libxft-dev

* Moved vcpkg.json/CMakePresets.json to root folder of project

* try default-features: false

* macos build: aclocal missing

https://nevio.medium.com/brew-install-autoconf-brew-install-automake-brew-install-libtool-c7a5fec47acf

* Error:   qtbase requires feature doubleconversion on windows!

* ../src/a0ae733b32-18e1e2c397.clean/meson.build:494:2: ERROR: Dependency "xrandr" not found, tried pkgconfig and cmake

* ../src/a0ae733b32-18e1e2c397.clean/meson.build:498:2: ERROR: Dependency "xi" not found, tried pkgconfig and cmake

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=66a5da35478de9a1edb0866201528523910548a6

* Try 2021-05-12 release version of vcpkg

5568f110b509a9fd90711978a7cb76bae75bb092

https://github.com/microsoft/vcpkg/commit/5568f110b509a9fd90711978a7cb76bae75bb092

* qt instead of qtbase

* try vcpkg 2021.12.01

* Error: qt:x64-linux@6.2.1 does not have required feature concurrent

* no feature selection for qt

* try qtbase again

* linux install libxi-dev

* ../src/a0ae733b32-18e1e2c397.clean/meson.build:500:2: ERROR: Dependency "xcursor" not found, tried pkgconfig and cmake

* linux install libxdamage-dev

  Run-time dependency xdamage found: NO (tried pkgconfig and cmake)

  ../src/a0ae733b32-18e1e2c397.clean/meson.build:501:2: ERROR: Dependency "xdamage" not found, tried pkgconfig and cmake

* linux install libxinerama-dev

Run-time dependency xinerama found: NO (tried pkgconfig and cmake)

  ../src/a0ae733b32-18e1e2c397.clean/meson.build:545:2: ERROR: Dependency "xinerama" not found, tried pkgconfig and cmake

* linux install libxkbcommon-dev

  ERROR: Feature "xkbcommon": Forcing to "ON" breaks its condition:
      XKB_FOUND
  Condition values dump:
      XKB_FOUND = "FALSE"

  CMake Error at cmake/QtBuildInformation.cmake:80 (message):
  Error:   Check the configuration messages for an error that has occurred.

* fix cmakeListsTxtPath

* linux install libxkbcommon-x11-dev

* Update build_cmake.yml

added libxcb-xrm-dev

* Update build_cmake.yml

linux install libx11-xcb-dev

* Linux install packages listed at:

https://github.com/microsoft/vcpkg/issues/15150

* Try using jurple install qt because the github runners run out of memory trying to build qt

* Try using jurple install qt because the github runners run out of memory trying to build qt

* Reenable installs

* qt 6.2.2

* Split github actions by platfrom

* linux: g++-10 / clang++12
windows: rename workflow

* fix runs-on

* set env cc/ccx

* - CI job names
- explicitly set CC/CCX for cmake step
- CI status badges in readmy

* !ccx

* ! still cxx

* "clang++-12"

* target_include_directories(FaceMorph PRIVATE ${CMAKE_SOURCE_DIR}/src)

* Only use windeployqt if we're on windows

* windeployqt: try to handle both the vcpkg case with windeployqt.debug.bat and the normal install case without debug/release split