@vcpkg.json specify required opencv4 modules
On linux got:
 Error: gstreamer:x64-linux@1.19.2#2 is only supported on '(windows | osx) & (x64 | x86)'

opencv[gstreamer] is a module that we do not need