Try to fix linux CI build
https://github.com/microsoft/vcpkg/issues/10381
https://github.com/StefanVK/FaceSwap/runs/4513100827?check_suite_focus=true

  Building package libepoxy[core]:x64-linux...
  -- libgles2-mesa-dev must be installed before libepoxy can build. Install it with "apt-get install libgles2-mesa-dev".
  -- Downloading https://github.com/anholt/libepoxy/archive/1.5.9.tar.gz -> anholt-libepoxy-1.5.9.tar.gz...
  -- Extracting source /home/runner/work/FaceSwap/b/vcpkg/downloads/anholt-libepoxy-1.5.9.tar.gz
  -- Using source at /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean
  -- Found external ninja('1.10.2').
  -- Getting CMake variables for x64-linux-dbg
  -- Getting CMake variables for x64-linux-rel
  -- Configuring x64-linux-dbg
  -- Configuring x64-linux-dbg done
  -- Configuring x64-linux-rel
  -- Configuring x64-linux-rel done
  -- Package x64-linux-dbg
  [LogCollection][Start]File:'/home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/package-x64-linux-dbg-out.log':
  [1/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --header --no-source --outputdir=include/epoxy ../src/1.5.9-fb4e410a2d.clean/registry/glx.xml
  [2/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --header --no-source --outputdir=include/epoxy ../src/1.5.9-fb4e410a2d.clean/registry/egl.xml
  [3/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --source --no-header --outputdir=src ../src/1.5.9-fb4e410a2d.clean/registry/egl.xml
  [4/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --source --no-header --outputdir=src ../src/1.5.9-fb4e410a2d.clean/registry/glx.xml
  [5/14] /home/runner/work/FaceSwap/b/vcpkg/buildtrees/libepoxy/src/1.5.9-fb4e410a2d.clean/src/gen_dispatch.py --header --no-source --outputdir=include/epoxy ../src/1.5.9-fb4e410a2d.clean/registry/gl.xml
  [6/14] /usr/bin/cc -Isrc/libepoxy.a.p -Isrc -I../src/1.5.9-fb4e410a2d.clean/src -Iinclude -I../src/1.5.9-fb4e410a2d.clean/include -Iinclude/epoxy -I/home/runner/work/FaceSwap/b/vcpkg_installed/x64-linux/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -fPIC -g -fPIC -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wlogical-op -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -Wno-int-conversion -MD -MQ src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o -MF src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o.d -o src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o -c src/egl_generated_dispatch.c
  FAILED: src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o
  /usr/bin/cc -Isrc/libepoxy.a.p -Isrc -I../src/1.5.9-fb4e410a2d.clean/src -Iinclude -I../src/1.5.9-fb4e410a2d.clean/include -Iinclude/epoxy -I/home/runner/work/FaceSwap/b/vcpkg_installed/x64-linux/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -fPIC -g -fPIC -Wpointer-arith -Wmissing-declarations -Wformat=2 -Wstrict-prototypes -Wmissing-prototypes -Wnested-externs -Wbad-function-cast -Wold-style-definition -Wdeclaration-after-statement -Wunused -Wuninitialized -Wshadow -Wmissing-noreturn -Wmissing-format-attribute -Wredundant-decls -Wlogical-op -Werror=implicit -Werror=nonnull -Werror=init-self -Werror=main -Werror=missing-braces -Werror=sequence-point -Werror=return-type -Werror=trigraphs -Werror=array-bounds -Werror=write-strings -Werror=address -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -fno-strict-aliasing -Wno-int-conversion -MD -MQ src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o -MF src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o.d -o src/libepoxy.a.p/meson-generated_.._egl_generated_dispatch.c.o -c src/egl_generated_dispatch.c
  In file included from ../src/1.5.9-fb4e410a2d.clean/include/epoxy/egl.h:46,
                   from ../src/1.5.9-fb4e410a2d.clean/src/dispatch_common.h:59,
                   from src/egl_generated_dispatch.c:11:
  Error: include/epoxy/egl_generated.h:11:10: fatal error: EGL/eglplatform.h: No such file or directory